Execució de Firebase CLI amb comanda en comptes d'Action

diff --git a/.github/workflows/firebase_distribute.yml b/.github/workflows/firebase_distribute.yml
--- a/.github/workflows/firebase_distribute.yml
+++ b/.github/workflows/firebase_distribute.yml
@@ -73,21 +73,33 @@ jobs:
       - name: Create .env file from ENV_FILE
         run: echo "${{ secrets.ENV_FILE }}" > .env
 
-      - name: Set up Flutter
-        uses: subosito/flutter-action@v2
-        with:
-          flutter-version: "3.38.3"
-          channel: "stable"
-          cache: true
+      # - name: Set up Flutter
+      #   uses: subosito/flutter-action@v2
+      #   with:
+      #     flutter-version: "3.38.3"
+      #     channel: "stable"
+      #     cache: true
 
-      - name: Build APK (debug)
-        run: flutter build apk --debug
+      # - name: Build APK (debug)
+      #   run: flutter build apk --debug
+
+      - name: Check if APK file is in expected location
+        run: |
+          if [ ! -f build/app/outputs/apk/debug/app-debug.apk ]; then
+            echo "Error: APK file not found at build/app/outputs/apk/debug/app-debug.apk"
+            exit 1
+          fi
 
       - name: Upload artifact to Firebase App Distribution
-        uses: wzieba/Firebase-Distribution-Github-Action@v1
-        with:
-          appId: ${{secrets.FIREBASE_APP_ID_ANDROID}}
-          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
-          groups: testers
-          file: build/app/outputs/apk/debug/app-debug.apk
-          debug: true
+        # uses: wzieba/Firebase-Distribution-Github-Action@v1
+        # with:
+        #   appId: ${{secrets.FIREBASE_APP_ID_ANDROID}}
+        #   serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
+        #   groups: testers
+        #   file: build/app/outputs/apk/debug/app-debug.apk
+        #   debug: true
+        env:
+          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
+        run: |
+          curl -sL https://firebase.tools | bash
+          firebase appdistribution:distribute build/app/outputs/apk/debug/app-debug.apk --app ${{ secrets.FIREBASE_APP_ID }} --groups testers
