Afegir gestió d'errors de tests amb testRocket al CI

diff --git a/.github/workflows/flutter_test.yml b/.github/workflows/flutter_test.yml
--- a/.github/workflows/flutter_test.yml
+++ b/.github/workflows/flutter_test.yml
@@ -40,8 +40,11 @@ jobs:
       - name: Setup testRocket
         run: dart pub global activate test_rocket
       - name: Run test with testRocket with coverage information
-        run: testRocket run --coverage
-        continue-on-error: true
+        run: |
+          if testRocket run --coverage 2>&1 | tee | grep -q "❌Test Error"; then
+            echo "TestRocket detected test errors"
+            exit 1
+          fi
       - name: Run tests with flutter test with coverage information (check for errors here if testRocket fails)
         run: flutter test --coverage
         if: failure()
